In [3]:
import numpy as np
import pyreadr
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [7]:
result = pyreadr.read_r('.\StJames_hab.rds')
df = result[None]
df['Wetland'] = np.where(df['Habitat']==2.0, 'nonwetland', 'wetland')
df

,Habitat,DEM,sDEM,hDEM,DSM,CHM,Aspect,Slope,Curvature,PlanCurv,ProfileCurv,NDVI,NDRE,NDWI,x,y,Wetland
0,1.0,18.596609,18.622410,18.596609,18.596609,0.000000,220.204926,0.282718,-7.620917,-7.436076,0.184842,0.740069,0.126273,-0.581894,689081.606492,23141.985899,wetland
1,1.0,18.852713,18.852713,18.852713,18.852713,0.000000,152.799408,1.943434,0.002119,0.001246,-0.000874,0.584242,0.125773,-0.588223,689061.811650,23140.486293,wetland
2,3.0,20.939791,21.091728,20.939791,23.523529,2.648577,337.529266,5.929980,-0.000000,-0.000000,0.000000,0.825232,0.204998,-0.667627,689063.611181,23114.393152,wetland
3,1.0,18.763475,18.600845,18.763475,20.473263,1.321201,262.127075,15.249783,0.004239,0.002263,-0.001976,0.459699,0.169193,-0.545694,689045.315949,23112.593625,wetland
4,1.0,18.332489,18.293556,18.379988,18.949297,0.000000,256.520172,15.954921,-13.741387,-3.217997,10.523391,0.631705,0.108272,-0.529282,689044.116261,23110.494177,wetland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,2.0,16.185696,16.108330,16.319582,16.185696,0.000000,187.272522,1.815900,49.468147,20.895496,-28.572649,0.473911,0.121286,-0.534078,689054.313604,22178.939065,nonwetland
104,3.0,16.280769,15.979391,16.427000,18.946585,4.668274,143.560349,7.051764,152.568817,166.965775,14.396961,0.844496,0.263951,-0.678592,689005.726264,22136.350260,wetland
105,2.0,16.497171,16.600376,16.497171,16.496794,-0.000378,240.189713,7.700943,54.963428,13.395777,-41.567654,0.572507,0.131399,-0.559735,689130.793676,22133.051128,nonwetland
106,2.0,16.704000,16.905821,16.704000,16.704000,0.000000,330.354675,2.663709,-18.840366,25.873678,44.714043,0.175782,0.095512,-0.173850,689158.386486,22114.755937,nonwetland
107,2.0,17.186844,17.401863,17.196396,19.879427,2.692583,70.795601,5.443464,-272.744507,-105.923210,166.821289,0.532320,0.044662,-0.244257,688969.135799,22084.463900,nonwetland

In [5]:
def jpt(dfes, x, y, hue, title):
    g = sns.jointplot(data=dfes, x=x, y=y, hue=hue)
    g.fig.suptitle(title)
    return g

In [12]:
# try to figure out a more efficient way to print relevant graphs

# for(columnName, columnData) in df.drop(["Habitat", "x","y", "Wetland"], axis=1).iteritems():
#     for(columnName1, columnData1) in df.drop(["Habitat", "x","y", "Wetland"], axis=1).iteritems():
#         if(columnName1 != columnName):
#             jpt(df, columnName1, columnName, 'Wetland', f'{columnName1} vs {columnName}')

IndentationError: expected an indented block (Temp/ipykernel_24968/3508536524.py, line 4)